limit_req_zone $binary_remote_addr zone=api:10m rate=10r/s;
server {
    listen 80;
    server_name localhost;
    root /var/www/html;
    index index.php;

    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;

    location /alive {
        return 200 "alive\n";
        add_header Content-Type text/plain;
    }

    location / {
        limit_req zone=api burst=20 nodelay;
        if ($request_method = 'OPTIONS')
        {
            add_header Access-Control-Allow-Origin "http://localhost:8000";
            add_header Access-Control-Allow-Methods "GET, POST, PATCH, DELETE, OPTIONS";
            add_header Access-Control-Allow-Headers "Content-Type, Authorization, Idempotency-Key";
            add_header Content-Length 0;
            add_header Content-Type application/json;
            return 204;
        }
        try_files $uri $uri/ /index.php?$query_string;
    }
    location ~ \.php$ {
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }

    location ~ /\.(env|git)
    {
        deny all;
        return 404;
    }
    
}